version: "3.3"

services:
  web: 
    image: gruppe1devops/moviedatabase
    restart: always
    depends_on: 
      - database

  database:
    build: ./db/docker
    #image: mcr.microsoft.com/mssql/server
    restart: always
    environment: 
      ACCEPT_EULA: "Y"
      SA_PASSWORD: HelloW0rld
      MSSQL_DB: MovieDatabase

  flyway:
    image: flyway/flyway
    command: migrate
    volumes:
      - ./db/sql:/flyway/sql
      - ./db/conf:/flyway/conf
    depends_on: 
      - database