version: "3.3"

services: 
  web:
    image: gruppe1devops/moviedatabase
    environment: 
      EnvironmentName: Production
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_DB_PORT: 1434
    ports: 
      - 80:80

  database:
    ports:
      - 1434:1433